# Generated by Django 4.2.9 on 2024-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('reciept_number', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=13)),
                ('amount', models.CharField(max_length=5)),
                ('years', models.CharField(max_length=9)),
            ],
        ),
    ]
