# Generated by Django 4.2.9 on 2024-01-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='reciept_number',
            new_name='receipt_number',
        ),
    ]
